### ISSUE TITLE
WebRTC in iOS: PeerConnection object failed to create with own STUN/TURN server

### ISSUE THREAD

**Issue by netwinIos** [Piasy/AppRTC-iOS#3]
My app works successfully if I am not using any ICEServers, or using Google's STUN & TURN servers.

When I pass my own servers (i.e. STUN & TURN) in configurations and create the "PeerConnection" object, it generates nil, please find my code from "ARDAppClient.m" file:

// Create peer connection.
NSString *value = _isLoopback ? @"false" : @"true";
NSDictionary *optionalConstraints = @{ @"DtlsSrtpKeyAgreement" : value };
RTCMediaConstraints *constraints =
  [[RTCMediaConstraints alloc]
      initWithMandatoryConstraints:nil
               optionalConstraints:optionalConstraints];

RTCConfiguration *config = [[RTCConfiguration alloc] init];
RTCCertificate *pcert = [RTCCertificate generateCertificateWithParams:@{
@"expires" : @100000,
@"name" : @"RSASSA-PKCS1-v1_5"
}];

config.iceServers = _iceServers;  // OWN STUN & STUN servers
config.sdpSemantics = RTCSdpSemanticsUnifiedPlan;
config.certificate = pcert;
config.bundlePolicy = RTCBundlePolicyMaxBundle; // For checking purpose
config.iceTransportPolicy = RTCIceTransportPolicyAll; // Default value

_peerConnection = [_factory peerConnectionWithConfiguration:config
                                                constraints:constraints
                                                   delegate:self]; 

> Here "_peerConnection" object generates nil for my IceServers, so the further code is not executed.

> If I removed iceServers while configuration (i.e. no iceServers) I can successfully connect to other peers and can do voice/video chat.

Confused about:  "**How ICEServers used, as without providing the ICEServer list, my voice/video calling works perfectly"**

**Comment by Piasy** [comment]
I find out WebRTC's official git repo works fine, so I'm going to remove this repo, sorry about that :(
